"""
Structured Prescription Schemas.
Represents the output contract of Entity Extraction (Phase 5) and downstream verification (Phases 7 & 8).
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field


class MedicationRoute(str, Enum):
    ORAL = "oral"
    INTRAVENOUS = "IV"
    INTRAMUSCULAR = "IM"
    SUBCUTANEOUS = "SC"
    TOPICAL = "topical"
    INHALATION = "inhalation"
    OPHTHALMIC = "ophthalmic"
    OTIC = "otic"
    OTHER = "other"
    UNKNOWN = "unknown"


class MedicationForm(str, Enum):
    TABLET = "tablet"
    CAPSULE = "capsule"
    SYRUP = "syrup"
    INJECTION = "injection"
    OINTMENT = "ointment"
    DROPS = "drops"
    INHALER = "inhaler"
    OTHER = "other"


class SafetySeverity(str, Enum):
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"


class SafetyWarning(BaseModel):
    """Safety alert generated by confidence gating, rule validators, or medical checks."""

    warning_id: str
    severity: SafetySeverity = SafetySeverity.LOW
    category: str = Field(
        ...,
        description="E.g., low_confidence, drug_interaction, dose_anomaly, strikethrough",
    )
    message: str
    field_reference: str | None = Field(
        default=None, description="Path or name of field triggering warning"
    )
    requires_manual_verification: bool = Field(default=False)


class NormalizedDosageTiming(BaseModel):
    """
    Standardized interpretation of medical shorthand (1-0-1, SOS, OD, BD, TDS, QID, HS, etc.).
    """

    raw_shorthand: str | None = Field(
        default=None, description="Original text e.g. '1-0-1' or 'TDS'"
    )
    morning: int = Field(default=0, description="Dose count in morning")
    afternoon: int = Field(default=0, description="Dose count in afternoon")
    night: int = Field(default=0, description="Dose count at night")
    is_as_needed_sos: bool = Field(
        default=False, description="True if marked SOS / as needed"
    )
    with_meals: str | None = Field(
        default=None, description="before_food, after_food, with_food, etc."
    )
    human_readable: str = Field(
        ...,
        description="Plain-language description e.g. '1 tablet morning and 1 tablet night after meals'",
    )


class MedicationItem(BaseModel):
    """Extracted medicine with normalized clinical fields."""

    medicine_id: str
    name: str = Field(..., description="Extracted brand or generic name")
    generic_name: str | None = Field(
        default=None, description="Mapped generic active ingredient"
    )
    strength: str | None = Field(default=None, description="E.g., 500mg, 1g, 250mg/5ml")
    form: MedicationForm = Field(default=MedicationForm.TABLET)
    route: MedicationRoute = Field(default=MedicationRoute.ORAL)
    raw_frequency: str | None = Field(
        default=None, description="Extracted frequency string"
    )
    timing: NormalizedDosageTiming | None = None
    duration: str | None = Field(
        default=None, description="E.g., 5 days, 2 weeks, ongoing"
    )
    special_instructions: str | None = Field(
        default=None, description="E.g., take with warm water, avoid dairy"
    )
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    is_struck_through: bool = Field(
        default=False, description="True if marked with a strikethrough/correction"
    )
    manually_verified: bool = Field(
        default=False, description="True if confirmed or corrected by user/doctor"
    )


class DiagnosisItem(BaseModel):
    """Condition, symptom, or diagnosis mentioned in clinical notes."""

    condition: str
    icd10_code: str | None = None
    notes: str | None = None
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)


class LabVitalItem(BaseModel):
    """Extracted test or lab reading (e.g., ESR, BP, HbA1c)."""

    test_name: str
    value: str
    unit: str | None = None
    reference_range: str | None = None


class StructuredPrescription(BaseModel):
    """
    Complete structured prescription payload produced by services/extraction.
    Used for UI rendering, timeline tracking, and RAG grounding.
    """

    prescription_id: str = Field(..., description="Unique prescription ID")
    document_id: str = Field(
        ..., description="Reference to RawPrescriptionText document_id"
    )
    prescription_date: str | None = Field(
        default=None, description="Parsed ISO date string (YYYY-MM-DD) if found"
    )
    doctor_info: dict[str, str] | None = Field(
        default=None, description="Doctor names, qualifications, clinic name"
    )
    medications: list[MedicationItem] = Field(default_factory=list)
    diagnoses: list[DiagnosisItem] = Field(default_factory=list)
    allergies: list[str] = Field(
        default_factory=list, description="Extracted drug or food allergies"
    )
    labs_and_vitals: list[LabVitalItem] = Field(default_factory=list)
    general_notes: str | None = Field(
        default=None, description="Other clinical advice, referrals, or disclaimers"
    )
    safety_warnings: list[SafetyWarning] = Field(default_factory=list)
    overall_confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    requires_human_review: bool = Field(
        default=False,
        description="True if confidence is low or critical anomaly flagged",
    )
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
